version: "3.9"
services:
  backend:
    image: '#image'
    container_name: zharya
    restart: always
    ports:
      - "80:2024"
      - "2024:2024"
    environment:
      SPRING_PROFILES_ACTIVE: main
      SERVER_PORT: 2024
      POSTGRES_DB: jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: zharyauser
      POSTGRES_PASSWORD: zharya11
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zharyauser
      POSTGRES_PASSWORD: zharya11
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  db_data:
  cache: